sudo: false
language: rust
rust:
  - nightly
  - beta
  - stable
script:
  - cargo build
  - cargo test
  - cargo test --features log-events
  - "if [ $TRAVIS_RUST_VERSION = nightly ]; then cargo test --features unstable; fi"
  - "if [ $TRAVIS_RUST_VERSION = nightly ]; then cargo test --features heap_size; fi"
  - "cd examples/summarize-events/ && cargo build"
notifications:
  webhooks: http://build.servo.org:54856/travis
