sudo: false
language: rust
rust:
  - 1.36.0
  - nightly
  - beta
  - stable
os:
  - linux
script:
  - cargo build
  - "if [ $TRAVIS_RUST_VERSION = nightly ]; then cargo test --features unstable; fi"
  - cargo test
  - "cd string-cache-codegen/ && cargo build && cd .."
