[package]

name = "string_cache"
version = "0.0.0"
authors = [ "The Servo Project Developers" ]

[features]

# Enable event logging for generating benchmark traces.
# See examples/event-log.
log-events = ["rustc-serialize"]

[dependencies]
rand = "0"
phf = "0.7"
phf_macros = "0.7"

[dependencies.rustc-serialize]
version = "0"
optional = true

[dependencies.string_cache_plugin]
path = "plugin"

[dependencies.lazy_static]
git = "https://github.com/Kimundi/lazy-static.rs"
