[package]

name = "string_cache"
version = "0.0.0"
authors = [ "The Servo Project Developers" ]

[features]

# Enable event logging for generating benchmark traces.
# See examples/event-log.
log-events = []

[dependencies]
phf = "0"
phf_macros = "0"
rand = "0"
xxhash = "0"

[dependencies.string_cache_plugin]
path = "plugin"

[dependencies.lazy_static]
git = "https://github.com/Kimundi/lazy-static.rs"
