[package]

name = "string-cache-summarize-events"
version = "0.0.0"
authors = [ "The Servo Project Developers" ]

[dependencies]
csv = "0"
rustc-serialize = "0"
phf_shared = "0.7.4"

[dependencies.string_cache]
path = "../.."
